version: "3.7"
services:
  proxy:
    image: uralm1/uwc-llng-proxy
    container_name: esv-proxy
    hostname: esv
    domainname: uwc.ufanet.ru
    networks:
      uwcnet:
        ipv4_address: 10.14.72.1
      default:
    dns:
      - 10.14.0.2
      - 10.14.0.4
    ports:
      - 444:443
    volumes:
      - /etc/ssl/certs/uwc.ufanet.ru.pem:/etc/ssl/certs/u.pem:ro
      - /etc/ssl/private/uwc.ufanet.ru-key.pem:/etc/ssl/private/u.key:ro
      - public:/opt/esv/public
    environment:
      - TZ=Asia/Yekaterinburg
      - PUBLIC_ROOT=/opt/esv/public
      - PROXY_ADDR=http://esv-app:3000/
    links:
      - app:esv-app
    restart: unless-stopped

  app:
    image: uralm1/esv
    container_name: esv
    volumes:
      - /srv/esv/esv.conf:/opt/esv/esv.conf:ro
      - public:/opt/esv/public
    environment:
      - TZ=Asia/Yekaterinburg
    links:
      - tsdb
    restart: unless-stopped

  cron:
    image: uralm1/esv
    container_name: esv-cron
    volumes:
      - /srv/esv/esv.conf:/opt/esv/esv.conf:ro
    environment:
      - TZ=Asia/Yekaterinburg
    user: root:root
    init: true
    command: crond -f -M /bin/true -l 8
    links:
      - tsdb
    restart: unless-stopped

  tsdb:
    image: influxdb:1.7
    container_name: influxdb
    volumes:
      - /srv/influxdb/db:/var/lib/influxdb
      - /srv/influxdb/backups:/backups
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
    restart: unless-stopped

volumes:
  public:

networks:
  uwcnet:
    external:
      name: uwcnet

