#!/bin/sh

ip1=beko.uwc.local
ip2=tsdb

echo "System startup precheck"
echo "Waiting for $ip1 goes online..."
for cc in `seq 90`
do
  if ping -c 1 $ip1 &>/dev/null
  then
    break
  fi
  #echo -n "$cc "
  sleep 2
done
echo "Waiting for $ip2 goes online..."
for cc in `seq 90`
do
  if ping -c 1 $ip2 &>/dev/null
  then
    break
  fi
  #echo -n "$cc "
  sleep 2
done
echo "All OK"
